// lib/qontrek/proof-events.ts
// Proof event creation and management aligned with PRD v3.4 Section 24

import {
  ProofEvent,
  ProofEventType,
  ProofEventCategory,
  EVENT_CATEGORIES,
  EVENT_DESCRIPTIONS,
} from '@/types/proof-event';

/**
 * Create a new proof event
 * PRD Section 24.4: authorityClaimed is ALWAYS false
 */
export function createProofEvent(
  params: Omit<ProofEvent, 'id' | 'timestamp' | 'authorityClaimed' | 'category'>
): ProofEvent {
  const category = EVENT_CATEGORIES[params.eventType];
  
  return {
    ...params,
    id: generateEventId(),
    timestamp: new Date().toISOString(),
    category,
    // PRD Section 24.4: Non-Authority Guarantee
    // "No event generated by the system constitutes approval, rejection, or submission to LPPSA"
    authorityClaimed: false,
  };
}

/**
 * Generate unique event ID
 */
function generateEventId(): string {
  return `evt_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * Generate simple hash for payload integrity
 */
export function generatePayloadHash(payload: unknown): string {
  const str = JSON.stringify(payload);
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  return `hash_${Math.abs(hash).toString(16)}`;
}

/**
 * Format proof event for display
 */
export function formatProofEvent(event: ProofEvent): {
  time: string;
  date: string;
  action: string;
  actor: string;
  category: string;
  categoryColor: string;
} {
  const timestamp = new Date(event.timestamp);
  
  const categoryColors: Record<ProofEventCategory, string> = {
    FACT: 'text-blue-500',
    DECLARE: 'text-green-500',
    DERIVED: 'text-purple-500',
  };
  
  const actorLabels: Record<string, string> = {
    buyer: 'Pembeli',
    agent: 'Ejen',
    developer: 'Pemaju',
    system: 'Sistem',
  };
  
  return {
    time: timestamp.toLocaleTimeString('ms-MY', { 
      hour: '2-digit', 
      minute: '2-digit' 
    }),
    date: timestamp.toLocaleDateString('ms-MY', { 
      day: 'numeric', 
      month: 'short' 
    }),
    action: EVENT_DESCRIPTIONS[event.eventType] || event.intent,
    actor: actorLabels[event.actor] || event.actor,
    category: event.category,
    categoryColor: categoryColors[event.category],
  };
}

/**
 * Create common proof events
 */
export const ProofEventFactory = {
  documentUploaded: (caseId: string, docType: string, actorId?: string): ProofEvent =>
    createProofEvent({
      eventType: 'DOC_UPLOADED',
      actor: 'buyer',
      actorId,
      intent: `Dokumen ${docType} dimuat naik`,
      caseId,
      humanConfirmationRequired: false,
    }),
    
  fieldAcknowledged: (caseId: string, fieldKey: string, actorId?: string): ProofEvent =>
    createProofEvent({
      eventType: 'FIELD_ACKNOWLEDGED',
      actor: 'buyer',
      actorId,
      intent: `Medan ${fieldKey} disahkan oleh pembeli`,
      caseId,
      humanConfirmationRequired: true,
    }),
    
  readinessComputed: (caseId: string, band: string): ProofEvent =>
    createProofEvent({
      eventType: 'READINESS_COMPUTED',
      actor: 'system',
      intent: `Isyarat kesediaan dijana: ${band.toUpperCase()}`,
      caseId,
      humanConfirmationRequired: false,
      metadata: { band },
    }),
    
  tacScheduled: (caseId: string, slot: { date: string; time: string }, actorId?: string): ProofEvent =>
    createProofEvent({
      eventType: 'PHASE_TRANSITIONED',
      actor: 'agent',
      actorId,
      intent: `TAC dijadualkan: ${slot.date} ${slot.time}`,
      caseId,
      humanConfirmationRequired: true,
      metadata: slot,
    }),
    
  tacConfirmed: (caseId: string, actorId?: string): ProofEvent =>
    createProofEvent({
      eventType: 'TAC_TIMESTAMP_RECORDED',
      actor: 'buyer',
      actorId,
      intent: 'Pengesahan TAC direkod (timestamp sahaja)',
      caseId,
      humanConfirmationRequired: true,
    }),
    
  submissionConfirmed: (caseId: string, actorId?: string): ProofEvent =>
    createProofEvent({
      eventType: 'SUBMISSION_CONFIRMED',
      actor: 'agent',
      actorId,
      intent: 'Agent mengesahkan penghantaran ke portal LPPSA',
      caseId,
      humanConfirmationRequired: true,
    }),
    
  phaseTransitioned: (caseId: string, fromPhase: string, toPhase: string): ProofEvent =>
    createProofEvent({
      eventType: 'PHASE_TRANSITIONED',
      actor: 'system',
      intent: `Fasa bertukar: ${fromPhase} → ${toPhase}`,
      caseId,
      humanConfirmationRequired: false,
      metadata: { fromPhase, toPhase },
    }),
};
