/**
 * CR-007: Mortgage Cases API
 *
 * GET /api/cases - List mortgage cases
 * POST /api/cases - Create a new mortgage case
 */

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { persistSession: false } }
);

type CaseStatus = 'new' | 'documents_pending' | 'documents_received' | 'under_review' |
  'submitted_bank' | 'bank_processing' | 'approved' | 'rejected' | 'completed' | 'cancelled';

interface CreateCaseRequest {
  developer_id: string;
  property_id?: string;
  unit_id?: string;
  buyer_name: string;
  buyer_ic?: string;
  buyer_phone?: string;
  buyer_email?: string;
  property_price?: number;
  loan_amount_requested?: number;
  income_declared?: number;
  assigned_agent_id?: string;
}

/**
 * GET: List mortgage cases
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);

    const developerId = searchParams.get('developer_id');
    const agentId = searchParams.get('agent_id');
    const status = searchParams.get('status');
    const limit = parseInt(searchParams.get('limit') || '50');
    const offset = parseInt(searchParams.get('offset') || '0');

    let query = supabase
      .from('mortgage_cases')
      .select(`
        *,
        developer:developers(id, company_name),
        property:properties(id, name, slug),
        unit:property_units(id, unit_no, price),
        agent:mortgage_agents(id, name, phone_display)
      `)
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1);

    if (developerId) {
      query = query.eq('developer_id', developerId);
    }
    if (agentId) {
      query = query.eq('assigned_agent_id', agentId);
    }
    if (status) {
      query = query.eq('status', status);
    }

    const { data, error } = await query;

    if (error) {
      console.error('Supabase error:', error);
      return NextResponse.json(
        { error: error.message, code: 'DB_ERROR' },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      data,
      meta: {
        count: data?.length || 0,
        limit,
        offset,
      },
    });
  } catch (error) {
    console.error('Cases GET error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

/**
 * POST: Create a new mortgage case
 */
export async function POST(request: NextRequest) {
  try {
    const body: CreateCaseRequest = await request.json();

    // Validate required fields
    if (!body.developer_id) {
      return NextResponse.json(
        { error: 'developer_id is required' },
        { status: 400 }
      );
    }
    if (!body.buyer_name) {
      return NextResponse.json(
        { error: 'buyer_name is required' },
        { status: 400 }
      );
    }

    // Insert case (case_ref is auto-generated by trigger)
    const { data, error } = await supabase
      .from('mortgage_cases')
      .insert({
        developer_id: body.developer_id,
        property_id: body.property_id || null,
        unit_id: body.unit_id || null,
        buyer_name: body.buyer_name,
        buyer_ic: body.buyer_ic,
        buyer_phone: body.buyer_phone,
        buyer_email: body.buyer_email,
        property_price: body.property_price,
        loan_amount_requested: body.loan_amount_requested,
        income_declared: body.income_declared,
        assigned_agent_id: body.assigned_agent_id,
        assigned_at: body.assigned_agent_id ? new Date().toISOString() : null,
        status: 'new',
      })
      .select()
      .single();

    if (error) {
      console.error('Supabase error:', error);

      if (error.code === '23503') {
        return NextResponse.json(
          { error: 'Invalid developer_id, property_id, unit_id, or agent_id', code: 'INVALID_REFERENCE' },
          { status: 400 }
        );
      }

      return NextResponse.json(
        { error: error.message, code: 'DB_ERROR' },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      data,
    }, { status: 201 });
  } catch (error) {
    console.error('Cases POST error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
