/**
 * CR-007: Mortgage Cases API
 * S5: Added buyer_hash for PDPA consent linkage (dual-key)
 * S6.3-N3: Added max pagination cap (100), total count, page number in response
 *
 * GET /api/cases - List mortgage cases
 * POST /api/cases - Create a new mortgage case + link consent records
 *
 * === S6.3 API CONTRACT (GET) ===
 * Response shape changed from:
 *   { success, data: Case[], meta: { count, limit, offset } }
 * To:
 *   { success, data: Case[], page, limit, total }
 * Where:
 *   - data    = array of cases for the current page
 *   - page    = 1-indexed page number
 *   - limit   = page size (capped at MAX_LIMIT=100)
 *   - total   = total matching cases across all pages
 */

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

// S6.3-N3: Pagination constants
const DEFAULT_LIMIT = 20;
const MAX_LIMIT = 100;

type CaseStatus = 'new' | 'documents_pending' | 'documents_received' | 'under_review' |
  'submitted_bank' | 'bank_processing' | 'approved' | 'rejected' | 'completed' | 'cancelled';

interface CreateCaseRequest {
  developer_id: string;
  property_id?: string;
  unit_id?: string;
  buyer_name: string;
  buyer_ic?: string;
  buyer_phone?: string;
  buyer_email?: string;
  property_price?: number;
  loan_amount_requested?: number;
  income_declared?: number;
  assigned_agent_id?: string;
  // S5: Dual-key consent linkage
  buyer_hash?: string;
  declared_phone?: string;
}

/**
 * GET: List mortgage cases
 */
export async function GET(request: NextRequest) {
  try {
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!,
      { auth: { persistSession: false } }
    );

    const { searchParams } = new URL(request.url);

    const developerId = searchParams.get('developer_id');
    const agentId = searchParams.get('agent_id');
    const buyerHash = searchParams.get('buyer_hash');
    const status = searchParams.get('status');

    // S6.3-N3: Page-based pagination with max cap
    const page = Math.max(1, parseInt(searchParams.get('page') || '1'));
    const rawLimit = parseInt(searchParams.get('limit') || String(DEFAULT_LIMIT));
    const limit = Math.min(Math.max(1, rawLimit), MAX_LIMIT);
    const offset = (page - 1) * limit;

    // S6.3-N3: Use { count: 'exact' } to get total row count
    let query = supabase
      .from('mortgage_cases')
      .select(`
        *,
        developer:developers(id, company_name),
        property:properties(id, name, slug),
        unit:property_units(id, unit_no, price),
        agent:mortgage_agents(id, name, phone_display)
      `, { count: 'exact' })
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1);

    if (developerId) {
      query = query.eq('developer_id', developerId);
    }
    if (agentId) {
      query = query.eq('assigned_agent_id', agentId);
    }
    if (buyerHash) {
      query = query.eq('buyer_hash', buyerHash);
    }
    if (status) {
      query = query.eq('status', status);
    }

    const { data, error, count } = await query;

    if (error) {
      console.error('Supabase error:', error);
      return NextResponse.json(
        { error: error.message, code: 'DB_ERROR' },
        { status: 500 }
      );
    }

    // S6.3-N3: New paginated response shape
    return NextResponse.json({
      success: true,
      data: data || [],
      page,
      limit,
      total: count ?? data?.length ?? 0,
    });
  } catch (error) {
    console.error('Cases GET error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

/**
 * POST: Create a new mortgage case
 */
export async function POST(request: NextRequest) {
  try {
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!,
      { auth: { persistSession: false } }
    );

    const body: CreateCaseRequest = await request.json();

    // Validate required fields
    if (!body.developer_id) {
      return NextResponse.json(
        { error: 'developer_id is required' },
        { status: 400 }
      );
    }
    if (!body.buyer_name) {
      return NextResponse.json(
        { error: 'buyer_name is required' },
        { status: 400 }
      );
    }

    // Insert case (case_ref is auto-generated by trigger)
    // S5: Include buyer_hash + declared_phone for consent linkage
    const { data, error } = await supabase
      .from('mortgage_cases')
      .insert({
        developer_id: body.developer_id,
        property_id: body.property_id || null,
        unit_id: body.unit_id || null,
        buyer_name: body.buyer_name,
        buyer_ic: body.buyer_ic,
        buyer_phone: body.buyer_phone,
        buyer_email: body.buyer_email,
        property_price: body.property_price,
        loan_amount_requested: body.loan_amount_requested,
        income_declared: body.income_declared,
        assigned_agent_id: body.assigned_agent_id,
        assigned_at: body.assigned_agent_id ? new Date().toISOString() : null,
        status: 'new',
        // S5: Dual-key fields
        buyer_hash: body.buyer_hash || null,
        declared_phone: body.declared_phone || body.buyer_phone || null,
      })
      .select()
      .single();

    if (error) {
      console.error('Supabase error:', error);

      if (error.code === '23503') {
        return NextResponse.json(
          { error: 'Invalid developer_id, property_id, unit_id, or agent_id', code: 'INVALID_REFERENCE' },
          { status: 400 }
        );
      }

      return NextResponse.json(
        { error: error.message, code: 'DB_ERROR' },
        { status: 500 }
      );
    }

    // S5: Backfill consent records with case_id (dual-key linkage)
    // This links previously-granted consents (keyed on buyer_hash) to the new case
    if (body.buyer_hash && data?.id) {
      const { error: consentError } = await supabase
        .from('consent_records')
        .update({ case_id: data.id })
        .eq('buyer_hash', body.buyer_hash)
        .is('case_id', null);

      if (consentError) {
        // Non-fatal: consent linkage failure shouldn't block case creation
        console.warn('Consent linkage warning:', consentError.message);
      }
    }

    return NextResponse.json({
      success: true,
      data,
    }, { status: 201 });
  } catch (error) {
    console.error('Cases POST error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
